apiVersion: v1
kind: Pod
metadata:
    name: ubuntu
spec:
    restartPolicy: Always
    containers:
    - name: ubuntu
      image: ubuntu:16.04
      command: ["/bin/bash"]
      stdin: true
      tty: true
      resources:
        requests:
            cpu: "4"
            memory: "1Gi"
        limits:
            cpu: "10"
            memory: "4Gi"
        resizePolicy:
            cpu: "LiveResizable"
            memory: "LiveResizable"
