apiVersion: v1
kind: Pod
metadata:
    name: ubuntu-reserved
    labels:
      reservation-test: test
spec:
    restartPolicy: Always
    containers:
    - name: ubuntu-reserved
      image: ubuntu:16.04
      command: ["/bin/bash"]
      stdin: true
      tty: true
      resources:
        limits:
            cpu: 10
            memory: "2Gi"
        requests:
            cpu: 2
            memory: "1Gi"
        resizePolicy:
            cpu: "LiveResizeable"
            memory: "LiveResizeable"
    resourceReservation:
      name: reservatoin
      resources:
        requests:
          cpu: 5
