apiVersion: v1
kind: Service
metadata:
  name: mongo-mem-crestart
  labels:
    name: mongo-mem-crestart
spec:
  ports:
  - port: 27016
    targetPort: 27016
  clusterIP: None
  selector:
    role: mongo-mem-crestart
